// Each entry: emoji + search keywords (Spanish and English mixed, lowercase).
export const EMOJI_DATA = [
  { e: "🎁", k: "regalo gift present" },
  { e: "🎉", k: "fiesta party celebracion celebration confetti" },
  { e: "🎊", k: "fiesta confetti party ball" },
  { e: "🏆", k: "trofeo trophy premio award win" },
  { e: "🥇", k: "medalla medal oro gold first" },
  { e: "⭐", k: "estrella star" },
  { e: "🌟", k: "estrella brillante glowing star" },
  { e: "✨", k: "brillo sparkles magia magic" },
  { e: "💝", k: "regalo corazon heart gift" },
  { e: "💖", k: "corazon heart sparkling love" },
  { e: "💕", k: "corazones hearts love amor" },
  { e: "💗", k: "corazon heart growing love" },
  { e: "💘", k: "corazon heart flecha arrow cupido cupid love" },
  { e: "❤️", k: "corazon heart love amor rojo red" },
  { e: "🧡", k: "corazon heart naranja orange love" },
  { e: "💛", k: "corazon heart amarillo yellow love" },
  { e: "💚", k: "corazon heart verde green love" },
  { e: "💙", k: "corazon heart azul blue love" },
  { e: "💜", k: "corazon heart violeta purple love" },
  { e: "🖤", k: "corazon heart negro black love" },
  { e: "💐", k: "flores bouquet flowers ramo" },
  { e: "🌹", k: "rosa rose flor flower" },
  { e: "🌷", k: "tulipan tulip flor flower" },
  { e: "🌻", k: "girasol sunflower flor flower" },
  { e: "🌸", k: "flor cherry blossom flower" },
  { e: "🍕", k: "pizza comida food" },
  { e: "🍔", k: "hamburguesa burger comida food" },
  { e: "🍟", k: "papas fritas fries comida food" },
  { e: "🌮", k: "taco comida food" },
  { e: "🍣", k: "sushi comida food" },
  { e: "🍰", k: "torta cake pastel postre dessert" },
  { e: "🎂", k: "torta birthday cake cumpleaños pastel" },
  { e: "🧁", k: "cupcake magdalena postre dessert" },
  { e: "🍩", k: "dona donut postre dessert" },
  { e: "🍪", k: "galleta cookie postre dessert" },
  { e: "🍫", k: "chocolate dulce candy" },
  { e: "🍿", k: "pochoclo popcorn palomitas cine movie" },
  { e: "🍽️", k: "cena dinner plato comida food restaurante restaurant" },
  { e: "🍷", k: "vino wine copa drink" },
  { e: "🥂", k: "brindis toast champagne copas cheers" },
  { e: "🍾", k: "champagne botella bottle celebracion celebration" },
  { e: "☕", k: "cafe coffee te tea" },
  { e: "🍵", k: "te tea" },
  { e: "🧋", k: "bubble tea boba" },
  { e: "🍹", k: "trago cocktail drink" },
  { e: "🍺", k: "cerveza beer drink" },
  { e: "🎬", k: "cine movie pelicula film clapper" },
  { e: "🎮", k: "juego game videojuego videogame control" },
  { e: "🎨", k: "arte art paleta palette pintura painting" },
  { e: "🎵", k: "musica music nota note" },
  { e: "🎶", k: "musica music notas notes" },
  { e: "🎧", k: "auriculares headphones musica music" },
  { e: "🎤", k: "microfono microphone karaoke canto sing" },
  { e: "📷", k: "camara camera foto photo" },
  { e: "📸", k: "camara camera foto photo flash" },
  { e: "🎥", k: "camara video film" },
  { e: "🎫", k: "boleto ticket entrada" },
  { e: "🎟️", k: "boleto ticket entrada" },
  { e: "🎳", k: "bowling boliche" },
  { e: "🎯", k: "diana target dardo dart" },
  { e: "🎱", k: "billar pool billiard" },
  { e: "🎨", k: "arte pintura art palette" },
  { e: "✈️", k: "avion plane viaje travel" },
  { e: "🧳", k: "valija maleta suitcase viaje travel" },
  { e: "🚗", k: "auto car viaje travel" },
  { e: "🚕", k: "taxi car" },
  { e: "🚲", k: "bici bicicleta bicycle" },
  { e: "🏖️", k: "playa beach vacaciones vacation" },
  { e: "🏝️", k: "isla island playa beach" },
  { e: "🏕️", k: "campamento camping" },
  { e: "⛰️", k: "montaña mountain" },
  { e: "🗻", k: "montaña mountain fuji" },
  { e: "🌅", k: "amanecer sunrise" },
  { e: "🌄", k: "amanecer montaña sunrise mountain" },
  { e: "🌆", k: "ciudad city atardecer sunset" },
  { e: "🌃", k: "noche night ciudad city" },
  { e: "🌉", k: "puente bridge" },
  { e: "🛏️", k: "cama bed dormir sleep descanso" },
  { e: "🛋️", k: "sofa couch descanso relax" },
  { e: "🛀", k: "baño bath relax spa" },
  { e: "💆", k: "masaje massage spa relax" },
  { e: "💅", k: "manicura nails spa" },
  { e: "🧖", k: "spa sauna relax" },
  { e: "🕯️", k: "vela candle romantico romantic" },
  { e: "🕰️", k: "reloj clock tiempo time" },
  { e: "⏰", k: "alarma alarm reloj clock" },
  { e: "📅", k: "calendario calendar fecha date" },
  { e: "📆", k: "calendario calendar fecha date" },
  { e: "🎈", k: "globo balloon fiesta party" },
  { e: "🎀", k: "moño ribbon bow regalo gift" },
  { e: "🧸", k: "oso peluche teddy bear" },
  { e: "🐶", k: "perro dog mascota pet" },
  { e: "🐱", k: "gato cat mascota pet" },
  { e: "🐰", k: "conejo rabbit bunny" },
  { e: "🦋", k: "mariposa butterfly" },
  { e: "🌈", k: "arcoiris rainbow" },
  { e: "🔥", k: "fuego fire hot" },
  { e: "💧", k: "gota drop agua water" },
  { e: "🌙", k: "luna moon noche night" },
  { e: "☀️", k: "sol sun dia day" },
  { e: "⛅", k: "nube cloud sol sun clima weather" },
  { e: "❄️", k: "nieve snow frio cold" },
  { e: "🍀", k: "trebol clover suerte luck" },
  { e: "🌳", k: "arbol tree" },
  { e: "🌴", k: "palmera palm tree playa beach" },
  { e: "💎", k: "diamante diamond joya gem" },
  { e: "💍", k: "anillo ring compromiso engagement" },
  { e: "👑", k: "corona crown rey king reina queen" },
  { e: "🔑", k: "llave key" },
  { e: "🗝️", k: "llave key vintage" },
  { e: "🎓", k: "graduacion graduation" },
  { e: "📚", k: "libros books estudio study" },
  { e: "📖", k: "libro book leer read" },
  { e: "✏️", k: "lapiz pencil escribir write" },
  { e: "🖊️", k: "boligrafo pen escribir write" },
  { e: "💻", k: "computadora laptop trabajo work" },
  { e: "📱", k: "celular telefono phone mobile" },
  { e: "📺", k: "tv television" },
  { e: "🕹️", k: "joystick juego game" },
  { e: "🏀", k: "basquet basketball deporte sport" },
  { e: "⚽", k: "futbol soccer football deporte sport" },
  { e: "🏈", k: "futbol americano football deporte sport" },
  { e: "🎾", k: "tenis tennis deporte sport" },
  { e: "🏐", k: "voley volleyball deporte sport" },
  { e: "🏓", k: "ping pong tenis mesa table tennis" },
  { e: "🏸", k: "badminton deporte sport" },
  { e: "🥊", k: "boxeo boxing deporte sport" },
  { e: "🏋️", k: "gimnasio gym pesas weights ejercicio exercise" },
  { e: "🧘", k: "yoga meditacion meditation relax" },
  { e: "🏃", k: "correr running ejercicio exercise" },
  { e: "🚴", k: "bici bicicleta cycling ejercicio exercise" },
  { e: "🏊", k: "nadar swimming pileta pool" },
  { e: "⛳", k: "golf deporte sport" },
  { e: "🎣", k: "pesca fishing" },
  { e: "🎿", k: "esqui ski nieve snow" },
  { e: "🏂", k: "snowboard nieve snow" },
  { e: "🛹", k: "skate skateboard" },
  { e: "🛴", k: "patineta scooter" },
  { e: "🎪", k: "circo circus" },
  { e: "🎭", k: "teatro theater mascara mask" },
  { e: "🎡", k: "rueda ferris wheel parque diversiones" },
  { e: "🎢", k: "montaña rusa roller coaster" },
  { e: "🎠", k: "calesita carousel" },
  { e: "🧩", k: "puzzle rompecabezas" },
  { e: "🎲", k: "dado dice juego game" },
  { e: "🃏", k: "carta card joker naipe" },
  { e: "🀄", k: "mahjong juego game" },
  { e: "🧵", k: "hilo thread costura sewing" },
  { e: "🧶", k: "lana yarn tejido knit" },
  { e: "🪁", k: "cometa kite" },
  { e: "🪀", k: "yoyo" },
  { e: "🛍️", k: "compras shopping bolsas bags" },
  { e: "👗", k: "vestido dress ropa clothes" },
  { e: "👠", k: "tacos heels zapatos shoes" },
  { e: "👟", k: "zapatillas sneakers zapatos shoes" },
  { e: "🕶️", k: "lentes sunglasses gafas" },
  { e: "💄", k: "labial lipstick maquillaje makeup" },
  { e: "💐", k: "ramo bouquet flores flowers" },
  { e: "🍽️", k: "cena dinner comida food" },
  { e: "🥘", k: "guiso comida food paella" },
  { e: "🍝", k: "pasta spaghetti comida food" },
  { e: "🥗", k: "ensalada salad comida food saludable healthy" },
  { e: "🍦", k: "helado icecream postre dessert" },
  { e: "🍭", k: "chupetin lollipop dulce candy" },
  { e: "🍬", k: "caramelo candy dulce" },
  { e: "🥐", k: "medialuna croissant desayuno breakfast" },
  { e: "🥞", k: "panqueque pancake desayuno breakfast" },
  { e: "🍳", k: "huevo egg desayuno breakfast" },
  { e: "🌭", k: "pancho hotdog comida food" },
  { e: "🥙", k: "wrap sandwich comida food" },
  { e: "🍜", k: "fideos noodles ramen comida food" },
];
