"""reemplazar play_sessions por players, agregar repeatable a questions

Revision ID: 2fdf76b2680a
Revises: 86ff028f3f03
Create Date: 2026-07-23 01:54:01.083750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fdf76b2680a"
down_revision: Union[str, Sequence[str], None] = "86ff028f3f03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experience_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["experiences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experience_id", "name", name="uq_player_per_experience"),
        sa.UniqueConstraint("token"),
    )
    op.add_column("answers", sa.Column("player_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("answers_play_session_id_fkey"), "answers", type_="foreignkey"
    )
    op.create_foreign_key(None, "answers", "players", ["player_id"], ["id"])
    op.drop_column("answers", "play_session_id")
    op.add_column("questions", sa.Column("repeatable", sa.Boolean(), nullable=True))
    op.add_column(
        "reward_selections", sa.Column("player_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("reward_selections_play_session_id_key"),
        "reward_selections",
        type_="unique",
    )
    op.drop_constraint(
        op.f("reward_selections_play_session_id_fkey"),
        "reward_selections",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "reward_selections", "players", ["player_id"], ["id"])
    op.drop_column("reward_selections", "play_session_id")
    op.drop_table("play_sessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "play_sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("experience_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("player_label", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_points", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["experiences.id"],
            name=op.f("play_sessions_experience_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("play_sessions_pkey")),
        sa.UniqueConstraint(
            "token",
            name=op.f("play_sessions_token_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.add_column(
        "reward_selections",
        sa.Column("play_session_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "reward_selections", type_="foreignkey")
    op.create_foreign_key(
        op.f("reward_selections_play_session_id_fkey"),
        "reward_selections",
        "play_sessions",
        ["play_session_id"],
        ["id"],
    )
    op.create_unique_constraint(
        op.f("reward_selections_play_session_id_key"),
        "reward_selections",
        ["play_session_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("reward_selections", "player_id")
    op.drop_column("questions", "repeatable")
    op.add_column(
        "answers",
        sa.Column("play_session_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("answers_play_session_id_fkey"),
        "answers",
        "play_sessions",
        ["play_session_id"],
        ["id"],
    )
    op.drop_column("answers", "player_id")
    op.drop_table("players")
    # ### end Alembic commands ###
